name: koolnet_no_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - cmocean
  - h5py
  - hyperopt
  - ipython
  - lightning
  - matplotlib
  - numpy
  - pandas
  - rich
  - scikit-learn
  - seaborn
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - tqdm
